# NOT-IMPLEMENTED
[ai]
# Token for open AI, used to intelligently judge the match if the items
openai_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

# REQUIRED. Right now only facebook is supported.
[marketplace.facebook]
# REQUIRED
username = 'username'
# REQUIRED
password = 'password'
# REQUIRED, can be specified for each search item
search_city = 'city'
# OPTIONAL, default to 30 minutes, time between repeated searches
search_interval = 30
# OPTIONAL, if specified, a random time will be chosen between search_interval and max_search_interval
max_search_interval = 60

# OPTIONAL string or list of strings, can be specified for each search item
acceptable_locations = ['city', 'surrounding city']
# OPTIONAL, string or list of strings, can be specified for each search item
notify = 'user1'
# NOT-IMPLEMENTED, string or list of strings, can be specified for each search item
exclude_sellers = []

# REQUIRED for notification
[notify.user1]
# REQUIRED, only pushbullet notification is supported now.
pushbullet_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

# Another user
[notify.user2]
pushbullet_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'


# OPTIONAL a product
[query.item2]
keywords = 'search word one'

# Complete item
[item.name1]
# REUIRED string or list of strings
keywords = ['search word one', 'search word two']

# OPTIONAL string or list of strings, default to all marketplaces
marketplace = 'facebook'
# OPTIONAL words that should not be in the title
exclude_keywords = ['exclude word one', 'exclude word two']
# OPTIONAL product specific user to notify
notify = 'user2'
# REQUIRED, can be specified for each search item
search_city = 'another city'
# OPTIONAL
acceptable_locations = ['another city', 'surrounding city']
# NOT-IMPLEMENTED
exclude_sellers = []
