[marketplace.facebook]
username = 'username'
password = 'password'
search_city = 'houston'

[item.name1]
keywords = 'search word one'

[user.user1]
pushbullet_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
