categories:
- productivity
icon_url: https://raw.githubusercontent.com/BoPeng/ai-marketplace-monitor/main/docs/icon.png
screenshots:
- https://raw.githubusercontent.com/BoPeng/ai-marketplace-monitor/main/docs/webui_screenshot.png
tags:
- facebook marketplace
- deals
- ai
- notifications
